/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        礐/GUI-BitmapConvert V3.96.
*        Compiled Jul 19 2005, 13:50:35
*          (c) 2002-2005  Micrium, Inc.
  www.micrium.com

  (c) 1998-2005  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: da
* Dimensions:  64 * 64
* NumColors:   4
*
**********************************************************************
*/

#include "stdlib.h"
#include "stdio.h"
#include "GUI.h"
#include "project.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

// #define RGB565(r,g,b) (((r) << 16) | ((g) << 8) | (b))
// #define RGB565(r,g,b) ((unsigned long)((b) << 16 | (g) << 8 | (r)))
// #define RGB565(r,g,b) ((unsigned short)(((r) & 0xF8)<< 8 | ((g) & 0xFC)<< 3 | ((b) & 0xF8) >> 3))
// #define RGB RGB565
extern GUI_CONST_STORAGE unsigned char acda[1024];
// extern GUI_CONST_STORAGE GUI_COLOR Colorsda[4];


extern GUI_CONST_STORAGE unsigned short acXHR3[8192];
extern GUI_CONST_STORAGE unsigned short acXHR4[8192];
extern GUI_CONST_STORAGE unsigned char acname[837];
extern GUI_CONST_STORAGE unsigned char achwg[126];
//extern GUI_CONST_STORAGE unsigned short actest1[1600];
// extern GUI_CONST_STORAGE unsigned short actest1[1600];
// extenrn GUI_CONST_STORAGE GUI_BITMAP bmXHR1;
// extern GUI_CONST_STORAGE GUI_BITMAP bmXHR2;
extern GUI_CONST_STORAGE GUI_BITMAP bmda;


void ShowLogo()
{
	short Colorshwg[2];
	short Colorsname[4];
	// short Colorsname[4];
	// short i1bpp[4] = {0,0xffffff,0xffff,0xffff};
	int i,k = 1,j = 0;
	char strout[60];

//RGB565(255,230,55);
	Colorsname[0] = RGB565(0,0,0);
	Colorsname[1] = RGB565(200,200,200);
	Colorsname[2] = RGB565(255,230,55);
	Colorsname[3] = RGB565(0,0,0);


	// Colorsname[0] = 0x000f00;//RGB565(0,255,0);
	// Colorsname[1] = RGB565(0,0,255);
	// Colorsname[2] = RGB565(255,0,0);
	// Colorsname[3] = RGB565(0,255,255);
	
	//MainTask3();
	//BUTTON_Create(0,0,40,40,123,1);
	
	LCD_L0_DrawBitmap(
			66,76,
			64,64,
			16,
			128,
			&acXHR3[0],
			1,
			NULL);
	LCD_L0_DrawBitmap(
			140,111,
			123,27,
			2,
			31,
			&acname[0],
			0,
			&Colorsname[0]);
	// while(1);
	snprintf(strout, 60, "Come on everyone.Follow me.");
	GUI_DispStringAt(strout, 70, 140); 
	Delay_ms(1200);
	snprintf(strout, 60, "Put your hands down.Show your buttocks.");
	GUI_DispStringAt(strout, 70, 140); 
	Delay_ms(2000);

	// 显示one,two,three 嘿喂狗
	snprintf(strout, 60, "one,                                     ");
	GUI_DispStringAt(strout, 70, 140); 
	Delay_ms(500);
	snprintf(strout, 60, "one,two,");
	GUI_DispStringAt(strout, 70, 140); 
	Delay_ms(500);


	snprintf(strout, 60, "one,two,three");
	GUI_DispStringAt(strout, 70, 140); 
	Delay_ms(500);
	Colorshwg[0] = 0;//RGB565(0,0,0);
	Colorshwg[1] = -1;//RGB565(255,255,255);

	LCD_L0_DrawBitmap(
		150,140,
		55,18,
		1,
		7,
		&achwg[0],
		0,
		&Colorshwg[0]);
	Delay_ms(500);

	// 清除one,two,three
	snprintf(strout, 60, "                           ");
	// 清除嘿喂狗
	GUI_DispStringAt(strout, 70, 140); 
	Colorshwg[0] = 0;
	Colorshwg[1] = 0;
	LCD_L0_DrawBitmap(
		150,140,
		55,18,
		1,
		7,
		&achwg[0],
		0,
		&Colorshwg[0]);

	// return ;
 	for ( i = 0; i < 8; i++) 
	{
		LCD_L0_DrawBitmap(
			66,76,
			64,64,
			16,
			128,
			&acXHR3[0],
			1,
			NULL);

		for (j = 0; j < 50;j++) {
			Colorsname[1] = RGB565(100+j*1,100+j*1,150+j*1);
			LCD_L0_DrawBitmap(
				140,111,
				123,27,
				2,
				31,
				&acname[0],
				0,
				&Colorsname[0]);
			Delay_ms(10);

		}
		
		LCD_L0_DrawBitmap(
			66,76,
			64,64,
			16,
			128,
			&acXHR4[0],
			1,
			NULL);

		switch(k) {
		case 2:
			GUI_DispStringAt("1.1.        ", 70, 140); // 显示文本
			break;
		case 3:
			GUI_DispStringAt("1.1.1        ", 70, 140); // 显示文本
			break;

		case 5:
			GUI_DispStringAt("1.1.1-2.1    ", 70, 140); // 显示文本
			break;
		default:
			k = 1;
			GUI_DispStringAt("1.        ", 70, 140); // 显示文本
			break;
		}
		k++;
		for (j = 50; j > 0;j--) {
			Colorsname[1] = RGB565(100+j*1,100+j*1,150+j*1);
			LCD_L0_DrawBitmap(
				140,111,
				123,27,
				2,
				31,
				&acname[0],
				0,
				&Colorsname[0]);
			Delay_ms(10);

		}
		
		if (k == 4) {
			GUI_DispStringAt("1.1.1-2.        ", 70, 140); // 显示文本
			k++;
		}
	
		//Delay_ms(500);

		

		

	
	}
	
	// LCD_L0_DrawBitmap(
	// 	0,0,
	// 	20,20,
	// 	16,
	// 	40,
	// 	&actest1[0],
	// 	0,
	// 	NULL);

}